// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD4I2RUQ_Yfaq4pLsDRjGrpw9H2ogF7FY',
    appId: '1:200749841595:web:ca7eb71e1dda1d22877d9e',
    messagingSenderId: '200749841595',
    projectId: 'corte-real-6b077',
    authDomain: 'corte-real-6b077.firebaseapp.com',
  storageBucket: 'corte-real-6b077.firebasestorage.app',
    measurementId: 'G-7SJC3VNKTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7WtrK1ty_CxjmDccfTipBY0KWJv4iScM',
    appId: '1:211952550292:android:7404b34f9131c8363acf81',
    messagingSenderId: '211952550292',
    projectId: 'corte-real-app',
    storageBucket: 'corte-real-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsPNcPtGwxCb3Ik0btpfEouQZAOFf78e0',
    appId: '1:211952550292:ios:086ed8f9a702e5e43acf81',
    messagingSenderId: '211952550292',
    projectId: 'corte-real-app',
    storageBucket: 'corte-real-app.firebasestorage.app',
    iosBundleId: 'com.example.barbeariaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsPNcPtGwxCb3Ik0btpfEouQZAOFf78e0',
    appId: '1:211952550292:ios:086ed8f9a702e5e43acf81',
    messagingSenderId: '211952550292',
    projectId: 'corte-real-app',
    storageBucket: 'corte-real-app.firebasestorage.app',
    iosBundleId: 'com.example.barbeariaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUjYZpjwHxOELQPwurn7HRaPvp-_w8x90',
    appId: '1:211952550292:web:677e7935588e1d9c3acf81',
    messagingSenderId: '211952550292',
    projectId: 'corte-real-app',
    authDomain: 'corte-real-app.firebaseapp.com',
    storageBucket: 'corte-real-app.firebasestorage.app',
    measurementId: 'G-L0MLQQQX27',
  );
}
